### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/infografia-de-hilos-CxrlosMX#2]
![INFOGRAFIA](https://user-images.githubusercontent.com/77459857/117833083-a79f9480-b23b-11eb-9f36-611563296d28.jpg)

**Comment by Anthony4523** [comment]
Calificación: 20

Calificó: Antonio González Hernández

**Comment by josealfredo79** [comment]
Bien hecho y revisado
